### ISSUE TITLE
Check roam-to-git version in GitHub action

### ISSUE THREAD

**Issue by agentydragon** [MatthieuBizien/roam-to-git#14]
Hi! Thanks for writing this.

I'm feeling a little bit nervous that the GitHub action template says: `pip install git+https://github.com/MatthieuBizien/roam-to-git.git`

This means that is @MatthieuBizien 's GitHub account ever gets compromised, the action that everyone using this script has executing with credentials to read from their personal Roam database will be executing potentially malicious code.

I don't know whether anything really that useful can be done against this.
What I'm personally going to do is just change my GitHub action to say:

```
pip install git+https://github.com/MatthieuBizien/roam-to-git.git@8628900c8429d2af8d7c2406b9eed94f23db9f8c
```

(that's `HEAD` as of time of me writing this). Skimming the code, it looks OK to me. (I don't know the state of Git hash security those days. Maybe a really motivated attacker could put in malicious code with the same Git hash. Oh well, fingers crossed...)

Maybe:

* roam-to-git could have signed releases.
* The GitHub action could try to jail the process to communicate only with Roam Research website?

I really don't know if this is even worth solving at this point but wanted to bring it up just in case.

**Comment by MatthieuBizien** [comment]
Hi @agentydragon, thanks for the issue, that's a fair point. The solution of using hash seems OK, because Github [took actions] for securing it. You can also clone that repository, and change `pip install` to your repository.

On my side, it's a responsibility I would rather not have. I'm confident on Github 2FA + the encryption of my hard drive, but there are always vectors of attack. But I don't know how to change that:
- Signed commits are always a best practice, but I don't know how to verify it with `pip install git+`. And it don't change anything if my computer itself is compromised.
- Jailbreaking a Github action network would be perfect, but I can't find anything for that. I will look into it more tomorrow.

**Comment by agentydragon** [comment]
I would feel a bit safer if the package were downloaded from a version in PyPI, not from the Git repo directly, though I'm not sure how warranted it is (i.e., don't know whether PyPI's security is better than GitHub).

**Comment by dexter-stpierre** [comment]
A simple solution for this is to simply for the project and install from your fork. And simply update your repo when the main one gets updated :)
