### ISSUE TITLE
An error has been caught in function '<module>', process 'MainProcess'

### ISSUE THREAD

**Issue by PJJPtx** [MatthieuBizien/roam-to-git#46]
I am getting the following error and cannot resolve.

`2020-08-27 02:28:03.015 | DEBUG    | roam_to_git.scrapping:scrap:253 - Scrapping finished
2020-08-27 02:28:03.101 | DEBUG    | roam_to_git.fs:save_markdowns:50 - Saving markdown to /home/runner/work/RoamNotes/RoamNotes/markdown
2020-08-27 02:28:03.138 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (2999), thread 'MainThread' (140571112994624):`

Has anyone else seen this? Any ideas on what to try?

**Comment by MatthieuBizien** [comment]
Hi @PJJPtx! Could you complete the full bug report template to help me understand the bug?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Traceback**
Please use http://gist.github.com/ or similar, and report the last line here.

**Run `roam-to-git --debug notes/` and report what you get.**
It should open a Chrome front-end, an do the scrapping. The repository content will not be modified. If applicable, add screenshots to help explain your problem.

**Please complete the following information:**
- OS: [e.g. MacOs, Linux]
- Do you use Github Action?
- Do you use multiple Roam databases?
- Does roam-to-git use to work for you? When precisely did it stopped to work?
- Does some backup runs are still working?

**Additional context**
Add any other context about the problem here.
