### ISSUE TITLE
/ in page name creates a directory

### ISSUE THREAD

**Issue by mmazur** [MatthieuBizien/roam-to-git#57]
**Describe the bug**
My `Someday/Maybe` page ends up being `{formatted/markdown}/Someday/Maybe.md`.

**Expected behavior**
I was expecting a file named something like `Someday%!@#$@#^!@3@@#$Maybe.md` with the `%!@#$@#^!@3@@#$` part representing a `/` in some obscure encoding. :)

**Please complete the following information:**
- [x] Github Actions

**Comment by everruler12** [comment]
You can rename your page with `／` (full-width slash) to get around this. Backslashes in page titles are [namespaces](https://forum.roamresearch.com/t/namespaces-how-do-they-work/276). I don't think this is an issue with roam-to-git, because it is how Roam's backend formats the export .zip, which roam-to-git downloads. It is convenient for namespaces such as `Book/Harry Potter`, so all books are in their own directory.

**Comment by mmazur** [comment]
ack, thx
