### ISSUE TITLE
Exceeded the maximum execution time of 15 minutes.

### ISSUE THREAD

**Issue by emilras** [MatthieuBizien/roam-to-git#78]
I have git-to-roam runing in a GitHub Action. It used to work, but since the 3rd of December, ~97 of all runs have been failing du to the maximum execution time of 15 minutes being exceeded.

An snippet of the logs from the latest failing job is found here: https://gist.github.com/emilras/b0b0deda67b92d7db9904dce1d33e63c

I have tried running roam-to-git --debug locally, but it throws an entirely diffrent error, that doesn't seem to be related: 
pyppeteer.errors.NetworkError: Protocol error (Runtime.evaluate): Cannot find context with specified id

I can do a manual Markdown export from Roam.

I have seen other issues that / in page titles can cause issues, so I have tried to move them from.

Any ideas to what is going on, or how I can help debug the issue further?

**Comment by everruler12** [comment]
After opening the sign-in page, it timeouts at `Fill email`. Try checking that your Secrets are correct.

**Comment by emilras** [comment]
@everruler12 Thank you for suggesting this! But I have updated my secrets, and I get the same behaviour.

**Comment by everruler12** [comment]
I would suggest testing with a new repo from scratch. With my [guide](https://eriknewhard.com/blog/backup-roam-in-github), you can copy the Secret key names exactly.

You can check that your credentials are correct by logging out and logging back in to your Roam account. Report back if the log fails at a different spot.

Also of note, `/` only causes issues when they are the first character in the page name, or possibly when doubled `//`. Otherwise, slasher are useful for [namespacing](https://forum.roamresearch.com/t/namespaces-how-do-they-work/276)

**Comment by emilras** [comment]
@everruler12 Thanks, great idea to start over. But unfortunately no change in behaviour, still not working from a GitHub action.

**Comment by KrisAcharya** [comment]
@emilras , try the solution in https://github.com/MatthieuBizien/roam-to-git/issues/76.
Worked for me.

**Comment by emilras** [comment]
@KrisAcharya Thank you so much, that did the trick.
